export const areasByCounty = {
    Baringo:["Eldama Ravine","Kabarnet Town"],
    Bomet:["Bomet Town","Sotik"],
    Bungoma:["Bumngoma Town","Kimilili",'Webuye'],
    Busia:['Busia Town','Malaba Town'],
    ElgeyoMarakwet:['Iten'],
    Embu:['Embu Town','Runyenjes'],
    Garissa:['Garissa Town'],
    HomaBay:['Homa Bay Town','Mbita','Ndhiwa','Oyugis'],
    Isiolo:['Isiolo Town'],
    Kajiado: ["Kajiado North - Kerarapon/Bulbul","Kajiado Town","Kiserian","Kitengela","Loitoktok","Ngong","Ongata Rongai"], 
    Kakamega:['Butere','Kakamega Town','Mumias','Sabatia'],
    Kericho:['Kericho Town','Litein'],
    Kiambu: ["Banana Hill/Mucatha","Cianda/Ndumberi/Tinganga","Gatundu Town","Githunguri/Ndumberi","Juja/Highpoint/Weiteithie","Kabete/Uthiru","Kamiti/Tatu City/owa","Kiambu Town/Kirigiti","Kikuyu/Gitaru/Kinyariri/Muguga","Kinoo/87/Muthiga/Rugiri/Nyanduna/Limuru/Muthaiga North/Muthaiga","Muthaiga/Ridgeways","Ndenderu/Kiambaa/Karura","Nyari/Gachie/Kitusuru","Ruaka/Two Rivers","Ruiru Town/Kimbo","Ruiru - Kihunguro/Bypass/Membley","Thika Town/Ngoingwa","Thindigua/Runda/Edenville/Four Ways","Toll/Kenyatta Rd/KU Boma","Wangige","Zambezi/Sigona"],
    Kilifi: ['Kilifi','Malindi','Mariakani','Mazeras','Vipingo','Watamu'],
    Kirinyaga:['Kagio','Kerugoya Town','Kutus','Mwea'],
    Kisii:['Keroka','Kisii Town','Ogembo'],
    Kisumu:['Ahero','Kaloleni/Nyalenda B/Railways','Kicomi/Pipeline','Kisumu CBD','Kisumu International Airport/Bandani/Brightlight','Kondele/Migosi/Lolwe/Carwash/Kibos','Mamboleo','Manyatta/Nyamasaria/Mowlem','Maseno','United Mall/Patel/Kibuye'],
    Kitui:['Kitui','Mwingi'],
    Kwale:['Diani/Ukunda','Kwale Town','Lunga Lunga'],
    Laikipia:['Nanyuki Town','Nyahururu'],
    Lamu:['Lamu','Mpeketoni'],
    Machakos:["Athiriver/Daystar University/KMTC","Joska","Kangundo","Machakos Town","Masii","Matuu","Syokimau/Mlolongo","Greatwall Gardens","Tala"],
    Makueni:['Emali Town','Kibwezi','Mtito Andei','Wote'],
    Marsabit:['Marsabit Town'],
    Meru:['Makutano','Maua','Meru Town','Nkubu'],
    Migori:['Awendo','Isebania','Kehancha','Migori Town','Rongo'],
    Mombasa:['Bombolulu','Changamwe-Migadini/Magongo/Portries','Changamwe-Mikindani/Jomvu','Ganjoni/Docks','Kisauni/Bamburi/Mtopanga','Kizingo/Mbaraki/Mama Ngina Drive','Kongowea/Nyali Links Road City','Likoni','Mshomoroni/Vikwatani/Kiembeni','Mvita-Mwembe Tayari/Majengo/Tononoka','Mvita-Tudor/Shimanzi','Nyali','Shanzu/Mtwapa/Utange'],
    Muranga:['Kabati','Kenol','Muranga Town'],
    Nairobi: ["A.S.K Showground/Wanye","Adams Arcade/Dagoretti Corner","Bahati/Viwandani/Jeri","Bomas/CUEA/Galleria","Buruburu/Hamza/Harambee","CBD - GPO/City Market/Nation Centre","CBD - KICC/Parliament/Kencom","CBD - Luthuli/Afya Centre/Ronald Ngala","CBD - UON/Globe/Koja/River Road","City Stadium/Makongeni/Mbotela","Dagoretti South - Ngand'o/Riruta","Donholm/Greenfields/Kayole/Nasra","Embakasi - Fedha","Embakasi East - Utawala/Mihango/GSU","Embakasi East - Cabanas Stage/Kyang'ombe/Southfield Mall","Embakasi East - Pipeline/Transami/Airport North RD","Embakasi North - Dandora/Kariobangi North","Embakasi South - Bunyala Road/South B","Embakasi South - Mombasa Road/Sameer Park/General Motors/ICD","Embakasi South - Landimawe/Kware/Pipeline","Garden Estate/Thome/Marurui","Gigiri/Village Market/UN","Githurai/Kahawa Sukari","Hurlingham/DOD/Yaya Center","Huruma/Kiamaiko/Mbatini/Ngei","Imara Daima/AA/Maziwa/Kwa Njenga","Kahawa Wendani/Kenyatta University","Kahawa West/Githurai 44","Kamukunji - Airbase/Mlango Kubwa","Kamukunji - Eastleigh/California/Shauri Moyo","Kamulu","Karen","Kariobangi South/Dandora/Airbase","Kasarani - Clay City/Kasarani/Mwiki","Kiahuria/Mwihoko","Kibra - Jamhuri/Woodley","Kibra - Makina/Sarangombe","Kileleshwa/Dennis Pritt/State hse RD","Kileleshwa/Riverside","Kilimani","Komarock/Kangundo Road/Saika/Obama","Laini Saba/Lindi/Makina/Sarangombe","Langata - Dam Estate/Nyayo Highrise/Ngumo","Langata - Otiende/Southlands/St Mary's","Lavington/Valley Arcade/James Gichuru","Lower Kabete/Kangemi/Mountain View","Lower Kabete/Kangemi/Mountain View/Loresho","Mihango/Njiru/Chokaa","Muthaiga/CID/Karura","Naivasha Rd/Kawangware/Gatina/Waithaka","Parklands/Highbridge","Railways/Muthurwa/BS/OTC","Roysambu/Zimmerman","Ruai Junction/Alpha Biz Park/Infinity Industrial Park","Ruai Town","Ruaraka Town","Ruaraka - Babadogo/Lucky Summer","Ruaraka - Mathare N./Survey/Utalii","Runda/Roslyn","Spring Valley/Kyuna","Starehe - Kariokor/Ziwani/Majengo/Gikomba",'Starehe - Ngara/Desai Road/Equity/Park Road',"Starehe - Pangani/Juja Road","Starehe - Pumwani/Madiwa","Umaja/Tena Estate/Nasra","Upperhill - Community/KNH","Upperhill - Kiambere Rd/Mara Rd/Elgon Rd/Lower Hill ","Westlands - Central","Westlands - Highbridge/Parklands",],
    Nakuru:['Bahati','Gilgil','Industrial Area/Langalanga/Shabab','Kabarak University','Kaptembwa/Kapkuresi/Soilo/Rvist','Kuresoi','Lanet/Pipeline/Barnabas','Mai Mahiu','Milimani/Pgh/Ngata Bridge/Baraka','Molo','Naivasha','Nakuru CBD','Nakuru West-Mercy Njeri/London','Njoro'],
    Nandi:['Kabsabet Town','Nandi Hills'],
    Narok:['Kilgoris','Narok Town'],
    Nyamira:['Nyamira Town'],
    Nyandarua:['Ol Kalou'],
    Nyeri:['Karatina/Iria-ini/Konyu/Magutu/Ngorano','Nyeri Town','Nyeri Town-Kiganjo/Kirichu','Othaya'],
    Samburu:['Maralal'],
    Siaya:['Bondo','Siaya Town','Ugunja'],
    TaitaTaveta:['Mwatate','Taveta','Voi','Wundanyi'],
    TanaRiver:['Bula','Hola'],
    TharakaNithi:['Chogoria','Chuka Town'],
    TransNzoia:['Kiminini','Kitale','Moi\'s Bridge' ],
    Turkana:['Lodwar'],
    UasinGishu:['Eldoret Town','Hawaii Munyaka','Huruma/Road Block/Maili Nne','KCC/Ilula/Kipkorgot','Kesses/Moi University Main Campus','Kimumu/University of Eldoret/Marura','Kisumu Road/Elgon View/Langas/Airport','Maili Tisa/Juakali/Soi/Nangili','Nairobi Rd/Kapsoya/MTRH','Tairi Mbili/Maili Nne','Uganda Road'],
    Vihiga:['Chavakali','Luanda','Majengo','Mbale'],
    WestPokot:['Kapenguria']

  };  